default['chef_vault_pki']['data_bag'] = 'chef_vault_pki'
default['chef_vault_pki']['ca'] = 'chef_vault_pki_ca'
default['chef_vault_pki']['expires'] = 3655
default['chef_vault_pki']['expires_factor'] = 60 * 60 * 24
default['chef_vault_pki']['key_size'] = 2048
default['chef_vault_pki']['path'] = '/opt/chef_vault_pki'
default['chef_vault_pki']['path_mode'] = 0755
default['chef_vault_pki']['path_recursive'] = false
default['chef_vault_pki']['ca_path'] = nil
default['chef_vault_pki']['ca_path_mode'] = nil
default['chef_vault_pki']['ca_path_recursive'] = nil
default['chef_vault_pki']['owner'] = 'root'
default['chef_vault_pki']['group'] = 'root'
default['chef_vault_pki']['public_mode'] = 0644
default['chef_vault_pki']['private_mode'] = 0600
default['chef_vault_pki']['bundle_ca'] = false
default['chef_vault_pki']['standalone'] = false
